/** Nepal domestic airports served by scheduled / charter carriers (CAAN network). */
export const DOMESTIC_CITIES = [
  "Kathmandu",
  "Pokhara",
  "Lukla",
  "Ramechhap",
  "Bharatpur",
  "Bhairahawa",
  "Nepalgunj",
  "Biratnagar",
  "Dhangadhi",
  "Bhadrapur",
  "Janakpur",
  "Tumlingtar",
  "Jomsom",
  "Manang",
  "Simara",
  "Phaplu",
  "Rumjatar",
  "Lamidanda",
  "Taplejung",
  "Bajura",
  "Bajhang",
  "Dolpa",
  "Jumla",
  "Simikot",
  "Talcha (Rara)",
  "Surkhet",
  "Mahendranagar",
  "Everest Region",
];

/**
 * Cities reachable on international tickets from Nepal (KTM hub + common
 * onward destinations travellers request quotes for).
 */
export const INTERNATIONAL_ORIGINS = ["Kathmandu", "Pokhara"];

export const INTERNATIONAL_DESTINATIONS = [
  // India
  "Delhi",
  "Mumbai",
  "Bengaluru",
  "Chennai",
  "Kolkata",
  "Hyderabad",
  "Ahmedabad",
  "Goa",
  "Jaipur",
  "Lucknow",
  "Varanasi",
  "Srinagar",
  "Kochi",
  "Trivandrum",
  "Pune",
  "Chandigarh",
  "Amritsar",
  // Gulf & Middle East
  "Dubai",
  "Abu Dhabi",
  "Sharjah",
  "Doha",
  "Riyadh",
  "Jeddah",
  "Dammam",
  "Medina",
  "Kuwait City",
  "Muscat",
  "Bahrain",
  "Istanbul",
  "Tel Aviv",
  "Cairo",
  // South & Southeast Asia
  "Singapore",
  "Kuala Lumpur",
  "Bangkok",
  "Phuket",
  "Chiang Mai",
  "Hong Kong",
  "Macau",
  "Guangzhou",
  "Shenzhen",
  "Shanghai",
  "Beijing",
  "Chengdu",
  "Kunming",
  "Lhasa",
  "Taipei",
  "Seoul",
  "Busan",
  "Tokyo",
  "Osaka",
  "Nagoya",
  "Manila",
  "Cebu",
  "Jakarta",
  "Bali (Denpasar)",
  "Hanoi",
  "Ho Chi Minh City",
  "Phnom Penh",
  "Yangon",
  "Colombo",
  "Malé",
  "Dhaka",
  // Europe
  "London",
  "Manchester",
  "Paris",
  "Frankfurt",
  "Munich",
  "Amsterdam",
  "Zurich",
  "Vienna",
  "Rome",
  "Milan",
  "Barcelona",
  "Madrid",
  "Brussels",
  "Copenhagen",
  "Stockholm",
  "Oslo",
  "Helsinki",
  "Dublin",
  "Athens",
  "Prague",
  "Warsaw",
  "Budapest",
  // Americas
  "New York",
  "Los Angeles",
  "San Francisco",
  "Chicago",
  "Washington DC",
  "Boston",
  "Toronto",
  "Vancouver",
  "Montreal",
  // Oceania
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Auckland",
];

export function mergeCityLists(base, dynamicValues = []) {
  return Array.from(new Set([...base, ...dynamicValues.filter(Boolean)])).sort((a, b) =>
    a.localeCompare(b)
  );
}
