/**
 * Seeds outbound international holiday packages (create-only upsert).
 * Existing CMS records are never updated — images and edits are preserved.
 */
export async function seedInternationalTours(prisma, now) {
  const packages = [
    {
      slug: "thailand-bangkok-phuket",
      title: "Thailand — Bangkok & Phuket Escape",
      shortDescription:
        "A week-long beach and city combo from Kathmandu: temples, street food, island hopping, and Andaman Sea sunsets.",
      description: `<p>Perfect for Nepali travellers seeking a short international break without a long-haul flight. This package combines Bangkok's energy with Phuket's beaches — ideal for families, couples, and first-time visitors to Thailand.</p>
<p>We handle flights from Kathmandu, airport transfers, hand-picked hotels, and daily support so you can focus on enjoying Thailand.</p>`,
      basePrice: 899,
      durationDays: 7,
      durationNights: 6,
      startPoint: "Kathmandu",
      endPoint: "Phuket",
      featuredImageUrl: "/assets/img/destination/destination_4_2.jpg",
      cardImageUrl: "/assets/img/destination/destination_4_2.jpg",
      highlights: [
        "Return flights KTM–BKK–HKT",
        "4★ hotels with daily breakfast",
        "Grand Palace & Wat Pho guided tour",
        "Phi Phi or James Bond Island day trip",
        "Visa assistance for Thai tourist visa",
      ],
      priceIncludes: [
        "Return international flights from Kathmandu",
        "Airport transfers in Bangkok & Phuket",
        "6 nights accommodation (3 BKK + 3 HKT)",
        "Daily breakfast",
        "Bangkok city sightseeing tour",
        "One full-day island excursion in Phuket",
      ],
      priceExcludes: [
        "Travel insurance",
        "Lunches and dinners unless stated",
        "Personal expenses & shopping",
        "Optional spa or adventure add-ons",
      ],
      itineraryDays: [
        { dayNumber: 1, title: "Fly Kathmandu → Bangkok", description: "<p>Evening arrival, meet & greet, transfer to hotel near Sukhumvit or Riverside.</p>", order: 0 },
        { dayNumber: 2, title: "Bangkok temples & markets", description: "<p>Grand Palace, Wat Pho, and optional Chao Phraya dinner cruise.</p>", order: 1 },
        { dayNumber: 3, title: "Bangkok free day", description: "<p>Chatuchak Market, MBK, or day trip to Ayutthaya (optional).</p>", order: 2 },
        { dayNumber: 4, title: "Fly to Phuket", description: "<p>Morning flight, beach resort check-in, sunset at Patong or Kata.</p>", order: 3 },
        { dayNumber: 5, title: "Island hopping", description: "<p>Full-day Phi Phi or James Bond Island speedboat tour with lunch.</p>", order: 4 },
        { dayNumber: 6, title: "Beach leisure", description: "<p>Relax, optional snorkelling, spa, or Big Buddha visit.</p>", order: 5 },
        { dayNumber: 7, title: "Return to Kathmandu", description: "<p>Transfer to Phuket airport for flight home via Bangkok.</p>", order: 6 },
      ],
      seoTitle: "Thailand Bangkok Phuket Package from Nepal",
      seoDescription: "7-day Thailand holiday from Kathmandu — Bangkok temples, Phuket beaches, flights and hotels included.",
    },
    {
      slug: "dubai-luxury-getaway",
      title: "Dubai — Luxury City & Desert Safari",
      shortDescription:
        "Skyscrapers, souks, and desert dunes — a 5-night Dubai package with Burj Khalifa, marina cruise, and safari.",
      description: `<p>Dubai is one of the most popular outbound destinations for Nepali travellers. This curated itinerary balances iconic sights with comfort — ideal for shopping, dining, and a taste of Arabian adventure.</p>`,
      basePrice: 1150,
      durationDays: 6,
      durationNights: 5,
      startPoint: "Kathmandu",
      endPoint: "Dubai",
      featuredImageUrl: "/assets/img/destination/destination_4_1.jpg",
      cardImageUrl: "/assets/img/destination/destination_4_1.jpg",
      highlights: [
        "Direct or one-stop flights from Kathmandu",
        "4–5★ city hotel near metro or Marina",
        "Burj Khalifa At the Top (Level 124)",
        "Evening desert safari with BBQ dinner",
        "Dubai Mall & Gold Souk visit",
      ],
      priceIncludes: [
        "Return flights Kathmandu–Dubai",
        "5 nights hotel with breakfast",
        "Airport transfers",
        "Desert safari with dune bashing & dinner",
        "Burj Khalifa ticket (standard level)",
      ],
      priceExcludes: [
        "UAE visa fees (we assist with application)",
        "Lunch & dinner except safari BBQ",
        "Theme park tickets (optional add-ons)",
        "Travel insurance",
      ],
      itineraryDays: [
        { dayNumber: 1, title: "Arrive Dubai", description: "<p>Airport pickup, hotel check-in, evening walk at Dubai Marina.</p>", order: 0 },
        { dayNumber: 2, title: "Old & new Dubai", description: "<p>Al Fahidi district, abra ride, Gold Souk, and Burj Khalifa at sunset.</p>", order: 1 },
        { dayNumber: 3, title: "Desert safari", description: "<p>Afternoon pickup for dune bashing, camel ride, and BBQ under the stars.</p>", order: 2 },
        { dayNumber: 4, title: "Shopping & leisure", description: "<p>Dubai Mall, Dubai Fountain show, optional Aquaventure or Ski Dubai.</p>", order: 3 },
        { dayNumber: 5, title: "Free day", description: "<p>Beach time at JBR, Palm Jumeirah monorail, or Abu Dhabi day trip (optional).</p>", order: 4 },
        { dayNumber: 6, title: "Departure", description: "<p>Transfer to DXB for flight to Kathmandu.</p>", order: 5 },
      ],
      seoTitle: "Dubai Tour Package from Nepal — Desert Safari & Burj Khalifa",
      seoDescription: "6-day Dubai holiday from Kathmandu with flights, hotel, desert safari, and Burj Khalifa.",
    },
    {
      slug: "maldives-island-retreat",
      title: "Maldives — Island Honeymoon Retreat",
      shortDescription:
        "Overwater vibes on a budget-friendly local island or resort — crystal lagoons, snorkelling, and pure relaxation.",
      description: `<p>The Maldives needs little introduction. We arrange flights via Colombo or direct connections, speedboat or seaplane transfers, and stays on hand-picked islands suited to your budget — from guesthouse islands to boutique resorts.</p>`,
      basePrice: 1499,
      durationDays: 5,
      durationNights: 4,
      startPoint: "Kathmandu",
      endPoint: "Malé",
      featuredImageUrl: "/assets/img/destination/destination_4_3.jpg",
      cardImageUrl: "/assets/img/destination/destination_4_3.jpg",
      highlights: [
        "Flights KTM–MLE with best available routing",
        "Speedboat or domestic flight + boat transfer",
        "Beach bungalow or resort room",
        "Snorkelling trip to house reef",
        "Honeymoon cake & room decoration (on request)",
      ],
      priceIncludes: [
        "Return flights to Malé",
        "4 nights island accommodation",
        "Return transfers to island",
        "Daily breakfast",
        "One snorkelling / sandbank excursion",
      ],
      priceExcludes: [
        "Seaplane supplement (if required by resort)",
        "Lunch, dinner & beverages",
        "Scuba diving & motorised water sports",
        "Green tax & service charges at resort",
      ],
      itineraryDays: [
        { dayNumber: 1, title: "Fly to Malé", description: "<p>Arrive Velana International, speedboat to island, check-in.</p>", order: 0 },
        { dayNumber: 2, title: "House reef snorkelling", description: "<p>Guided snorkelling, beach time, optional sunset fishing.</p>", order: 1 },
        { dayNumber: 3, title: "Sandbank or local island", description: "<p>Half-day trip to sandbank picnic or visit to local fishing village.</p>", order: 2 },
        { dayNumber: 4, title: "Spa & relaxation", description: "<p>Free day — spa, kayaking, or diving certification (optional).</p>", order: 3 },
        { dayNumber: 5, title: "Return home", description: "<p>Boat to airport, flight to Kathmandu.</p>", order: 4 },
      ],
      seoTitle: "Maldives Honeymoon Package from Nepal",
      seoDescription: "5-day Maldives island package from Kathmandu — flights, transfers, snorkelling, and beach stay.",
    },
    {
      slug: "bali-culture-beaches",
      title: "Bali — Culture, Rice Terraces & Beaches",
      shortDescription:
        "Ubud temples, Tegallalang rice terraces, and Seminyak beaches — Indonesia's island paradise in one trip.",
      description: `<p>Bali offers incredible value for Nepali travellers — rich Hindu culture, world-class surfing, and wellness retreats. This route covers Ubud's heartland and south-coast beaches with private transfers throughout.</p>`,
      basePrice: 980,
      durationDays: 8,
      durationNights: 7,
      startPoint: "Kathmandu",
      endPoint: "Denpasar",
      featuredImageUrl: "/assets/img/tour/tour_4_3.jpg",
      cardImageUrl: "/assets/img/tour/tour_4_3.jpg",
      highlights: [
        "Flights KTM–DPS (via Singapore/KL)",
        "Ubud boutique hotel + Seminyak beach stay",
        "Tegallalang rice terrace & Ubud Monkey Forest",
        "Tanah Lot sunset temple visit",
        "Optional Mount Batur sunrise trek",
      ],
      priceIncludes: [
        "Return international flights",
        "7 nights accommodation (split Ubud/Seminyak)",
        "Private airport transfers",
        "Daily breakfast",
        "Full-day Ubud cultural tour",
        "Tanah Lot sunset excursion",
      ],
      priceExcludes: [
        "Indonesia visa on arrival",
        "Lunches & dinners",
        "Mount Batur trek (optional)",
        "Travel insurance",
      ],
      itineraryDays: [
        { dayNumber: 1, title: "Arrive Bali", description: "<p>Transfer to Ubud, welcome drink, evening at leisure.</p>", order: 0 },
        { dayNumber: 2, title: "Ubud highlights", description: "<p>Rice terraces, Monkey Forest, art markets, and royal palace.</p>", order: 1 },
        { dayNumber: 3, title: "Water temples", description: "<p>Tirta Empul holy spring temple and scenic drives through villages.</p>", order: 2 },
        { dayNumber: 4, title: "Move to Seminyak", description: "<p>Check-in to beach area, afternoon pool and sunset beach walk.</p>", order: 3 },
        { dayNumber: 5, title: "Tanah Lot & Uluwatu", description: "<p>Coastal temple tour ending with Kecak fire dance at Uluwatu.</p>", order: 4 },
        { dayNumber: 6, title: "Beach day", description: "<p>Surf lesson, spa, or Nusa Penida day trip (optional).</p>", order: 5 },
        { dayNumber: 7, title: "Free day", description: "<p>Shopping in Seminyak or revisit favourite spots.</p>", order: 6 },
        { dayNumber: 8, title: "Departure", description: "<p>Transfer to Ngurah Rai airport for flight home.</p>", order: 7 },
      ],
      seoTitle: "Bali Tour Package from Nepal — Ubud & Beaches",
      seoDescription: "8-day Bali holiday from Kathmandu with Ubud culture, rice terraces, and Seminyak beaches.",
    },
    {
      slug: "singapore-city-break",
      title: "Singapore — City Break & Sentosa",
      shortDescription:
        "Clean, safe, and compact — perfect 4-night city break with Marina Bay, Gardens by the Bay, and Sentosa fun.",
      description: `<p>Singapore is ideal for families and first-time international travellers from Nepal. Short flight, excellent public transport, and attractions for all ages — from Gardens by the Bay to Universal Studios.</p>`,
      basePrice: 750,
      durationDays: 5,
      durationNights: 4,
      startPoint: "Kathmandu",
      endPoint: "Singapore",
      featuredImageUrl: "/assets/img/tour/tour_4_5.jpg",
      cardImageUrl: "/assets/img/tour/tour_4_5.jpg",
      highlights: [
        "Flights KTM–SIN",
        "Central hotel near MRT",
        "Gardens by the Bay & Marina Bay Sands skydeck",
        "Sentosa Island day pass",
        "Hawker centre food trail",
      ],
      priceIncludes: [
        "Return flights",
        "4 nights hotel with breakfast",
        "Airport transfers",
        "Gardens by the Bay entry",
        "Sentosa day pass with transfers",
      ],
      priceExcludes: [
        "Singapore visa (if required — many passports visa-free)",
        "Meals except breakfast",
        "Universal Studios ticket (optional)",
        "Travel insurance",
      ],
      itineraryDays: [
        { dayNumber: 1, title: "Arrive Singapore", description: "<p>Changi arrival, hotel check-in, evening at Merlion Park.</p>", order: 0 },
        { dayNumber: 2, title: "Marina Bay", description: "<p>Gardens by the Bay, Cloud Forest, evening light show.</p>", order: 1 },
        { dayNumber: 3, title: "Sentosa", description: "<p>Beach, cable car, and S.E.A. Aquarium or adventure park.</p>", order: 2 },
        { dayNumber: 4, title: "Culture & food", description: "<p>Chinatown, Little India, hawker centres, optional night safari.</p>", order: 3 },
        { dayNumber: 5, title: "Departure", description: "<p>Last-minute shopping at Orchard Road, flight to Kathmandu.</p>", order: 4 },
      ],
      seoTitle: "Singapore Package from Nepal — City & Sentosa",
      seoDescription: "5-day Singapore city break from Kathmandu with Marina Bay, Gardens by the Bay, and Sentosa.",
    },
    {
      slug: "japan-tokyo-kyoto",
      title: "Japan — Tokyo & Kyoto Discovery",
      shortDescription:
        "Cherry blossoms or autumn colours — bullet trains, temples, sushi, and the best of Japan in 9 days.",
      description: `<p>Japan fascinates Nepali travellers with its blend of tradition and technology. This package covers Tokyo's neon districts and Kyoto's zen gardens, with a Shinkansen ride between cities and English-speaking guides on key days.</p>`,
      basePrice: 1899,
      durationDays: 9,
      durationNights: 8,
      startPoint: "Kathmandu",
      endPoint: "Tokyo",
      featuredImageUrl: "/assets/img/tour/tour_4_4.jpg",
      cardImageUrl: "/assets/img/tour/tour_4_4.jpg",
      highlights: [
        "Flights KTM–TYO (via connecting hub)",
        "JR Pass or bullet train Tokyo–Kyoto",
        "Shibuya, Senso-ji Temple, teamLab (seasonal)",
        "Fushimi Inari & Arashiyama bamboo grove",
        "Japanese cuisine experiences",
      ],
      priceIncludes: [
        "Return international flights",
        "8 nights hotel (4 Tokyo + 4 Kyoto)",
        "Airport transfers",
        "Bullet train Tokyo–Kyoto one-way",
        "Guided Tokyo & Kyoto orientation days",
        "Daily breakfast",
      ],
      priceExcludes: [
        "Japan visa (we provide invitation support)",
        "Lunches & dinners",
        "Personal rail pass upgrades",
        "Travel insurance",
      ],
      itineraryDays: [
        { dayNumber: 1, title: "Arrive Tokyo", description: "<p>Narita/Haneda pickup, hotel in Shinjuku or Shibuya.</p>", order: 0 },
        { dayNumber: 2, title: "Tokyo classics", description: "<p>Senso-ji, Asakusa, Tokyo Skytree or teamLab Borderless.</p>", order: 1 },
        { dayNumber: 3, title: "Modern Tokyo", description: "<p>Shibuya Crossing, Harajuku, Meiji Shrine, optional robot restaurant.</p>", order: 2 },
        { dayNumber: 4, title: "Day trip or free", description: "<p>Mt. Fuji Hakone tour (optional) or explore Akihabara & Ginza.</p>", order: 3 },
        { dayNumber: 5, title: "Bullet train to Kyoto", description: "<p>Shinkansen ride, check-in, evening Gion district walk.</p>", order: 4 },
        { dayNumber: 6, title: "Kyoto temples", description: "<p>Fushimi Inari, Kiyomizu-dera, and traditional tea ceremony.</p>", order: 5 },
        { dayNumber: 7, title: "Arashiyama", description: "<p>Bamboo grove, Tenryu-ji, and optional monkey park.</p>", order: 6 },
        { dayNumber: 8, title: "Nara day trip", description: "<p>Todai-ji Great Buddha and deer park (optional).</p>", order: 7 },
        { dayNumber: 9, title: "Return via Tokyo", description: "<p>Shinkansen to Tokyo airport, flight to Kathmandu.</p>", order: 8 },
      ],
      seoTitle: "Japan Tokyo Kyoto Tour from Nepal",
      seoDescription: "9-day Japan package from Kathmandu — Tokyo, Kyoto, bullet train, temples, and guided sightseeing.",
    },
  ];

  for (const pkg of packages) {
    const { itineraryDays, ...tourData } = pkg;
    // eslint-disable-next-line no-await-in-loop
    const existing = await prisma.tour.findUnique({ where: { slug: pkg.slug } });
    if (existing) continue;

    // eslint-disable-next-line no-await-in-loop
    await prisma.tour.create({
      data: {
        ...tourData,
        market: "international",
        status: "PUBLISHED",
        isFeatured: true,
        publishedAt: now(),
        difficulty: "EASY",
        itineraryDays: {
          create: itineraryDays.map((d) => ({
            dayNumber: d.dayNumber,
            title: d.title,
            description: d.description,
            order: d.order,
          })),
        },
      },
    });
  }
}
